spring.application.name=wordtreasure

spring.datasource.url=jdbc:mysql://wordtreasure.mysql.database.azure.com:3306/test
spring.datasource.username=jsh
spring.datasource.password=qwer1234!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 ?? ?? ??? ??? ??
# spring.h2.console.enabled=false
# spring.datasource.driver-class-name=org.h2.Driver
